### ISSUE TITLE
Couldn't find 'shadowJar,'

### ISSUE THREAD

**Issue by Touma-Kazusa2** [EchoInMirror/EchoInMirror#24]
Hey, it seems I goofed up. I couldn't locate 'shadowJar,' so I tried the 'knows' task in Shadow. Ended up with a daw-jvm-0.0.0.jar that's causing errors when I run it. Any idea where I messed up?
![1](https://github.com/EchoInMirror/EchoInMirror/assets/126475460/1c7d80b6-8837-4b07-8464-301ded329b05)
![2](https://github.com/EchoInMirror/EchoInMirror/assets/126475460/7991d45d-7d88-4a39-b217-d4ac7a304537)
![3](https://github.com/EchoInMirror/EchoInMirror/assets/126475460/71a95f3a-7670-4a46-8f54-4abe896da920)

Run Main.kt is ok.

![4](https://github.com/EchoInMirror/EchoInMirror/assets/126475460/fbab43a8-d902-4fcd-9fb0-aa727f321e25)

**Comment by ShirasawaSama** [comment]
Possible incompatibility caused by Gradle version (8.4) and Shadow version (8.1.1).

https://github.com/johnrengelman/shadow/pull/876

However, the application is still in the development stage, so packaging is not required for the time being. You can pack it after they repair it.

**Comment by Touma-Kazusa2** [comment]
Thank you for your response. I find the work you're doing impressive. I hope your team achieves great success in your endeavors.

**Comment by ShirasawaSama** [comment]
Fixed in #26
